/* DIE TIEFE: 64 Tore und 6 Linien
   Jeder Tortext folgt einem Bogen: Kern, wie es sich zeigt, wo der Schatten liegt.
   Kein Text ist gegen einen anderen austauschbar. Kleines du, keine Gedankenstriche. */
(function(root,factory){
  if(typeof module!=="undefined"&&module.exports)module.exports=factory();
  else root.HDTiefe=factory();
})(typeof self!=="undefined"?self:this,function(){
"use strict";

var TOR_TEXTE={
1:"In dir arbeitet ein schöpferischer Kern, der sich ausdrücken muss wie andere atmen. Was du erschaffst, braucht kein Publikum, um wahr zu sein, aber es braucht Raum. Der Schatten: Du wartest auf Stimmung oder Erlaubnis, und das Werk bleibt in dir stecken, wo es gärt statt leuchtet.",
2:"Du bist wie die Fahrerin im Auto: Du kennst die Richtung, auch wenn du den Motor nicht selbst stellst. Menschen spüren, dass du weißt, wohin es geht, und richten sich danach aus. Der Schatten: Du lässt dich von lauteren Stimmen vom Kurs drängen, obwohl dein innerer Kompass längst zeigt.",
3:"Am Anfang steht bei dir das Chaos, und das ist kein Fehler, sondern Rohmaterial. Du ordnest Neues, indem du es durcheinanderwirbelst, bis eine Form entsteht, die vorher niemand sehen konnte. Der Schatten: Ungeduld mit dem eigenen Durcheinander, als müsste Neues fertig geboren werden.",
4:"Dein Kopf produziert Antworten wie eine Quelle Wasser: Formeln, Erklärungen, Lösungen auf Verdacht. Das ist ein Geschenk für alle, die an Fragen verzweifeln. Der Schatten: Du verwechselst die Formel mit der Wahrheit und verteidigst eine Antwort, die nur ein Versuch war.",
5:"Du lebst in Rhythmen, und dein Rhythmus ist heilig. Feste Zeiten, wiederkehrende Rituale, der immer gleiche Weg zur Arbeit: Was für andere Routine ist, ist für dich Kraftquelle. Der Schatten: Wer deinen Takt stört, stört dein Fundament, und du merkst es oft erst an der Erschöpfung.",
6:"Du bist die Membran zwischen innen und außen: Du entscheidest, wer dir nah kommt und wann. Reibung ist bei dir kein Unfall, sondern der Weg, auf dem Intimität entsteht. Der Schatten: Du machst dicht, bevor die Reibung ihre Arbeit tun konnte, und nennst es Frieden.",
7:"Führung liegt bei dir nicht im Titel, sondern im Blick für die Richtung, die eine Gruppe braucht. Man fragt dich, wohin es gehen soll, oft ohne zu merken, dass man fragt. Der Schatten: Du drängst deine Richtung auf, statt gewählt zu werden, und wunderst dich über Widerstand.",
8:"Dein Beitrag ist, sichtbar zu machen, was einzigartig ist: an dir, an anderen, an einer Sache. Du bist Verstärker für das Echte. Der Schatten: Du hältst deinen eigenen Ton zurück und promotest nur Fremdes, bis du dich fragst, wo du selbst geblieben bist.",
9:"Du kannst dich in ein Detail versenken, bis es seine Geheimnisse hergibt. Konzentration ist deine Form von Hingabe. Der Schatten: Du verzettelst dich im Kleinen und verlierst das Ganze aus dem Blick, oder du zerstreust dich, weil das Detail dich nicht gewählt hat.",
10:"Dieses Tor trägt die schwerste und schönste Frage: Kannst du dich selbst lieben, so wie du dich verhältst, wenn niemand zusieht? Dein Verhalten ist deine Botschaft, lauter als jedes Wort. Der Schatten: Du passt dein Verhalten an, um geliebt zu werden, und verlierst genau dadurch die Selbstachtung, um die es geht.",
11:"Ideen fliegen dir zu wie Vögel ans Fenster: bunt, viele, nicht alle zum Behalten. Du bist ein Gefäß für Bilder und Konzepte, die andere inspirieren. Der Schatten: Du glaubst, jede Idee selbst umsetzen zu müssen, dabei sind die meisten Geschichten zum Verschenken da.",
12:"Deine Stimme hat Farbe, aber nur, wenn die Stimmung stimmt. Du bist kein Dauersender, du bist ein Instrument, das gestimmt sein will. In den richtigen Momenten bewegst du Menschen mit einem Satz. Der Schatten: Du sprichst gegen deine Stimmung an und klingst hohl, oder du schweigst so lange, bis man dich vergisst.",
13:"Menschen erzählen dir Dinge, die sie sonst niemandem sagen. Du bist der Zeuge, das Ohr, das Archiv der Geschichten. Aus dem Gehörten formst du Sinn. Der Schatten: Du trägst fremde Geheimnisse wie eigene Lasten und vergisst, dass Zuhören nicht heißt, alles behalten zu müssen.",
14:"Du sitzt auf einer Kraftquelle: die Fähigkeit, Ressourcen zu mehren, wenn du für das Richtige arbeitest. Wohlstand folgt bei dir der Liebe zur Arbeit, nicht dem Zwang. Der Schatten: Du schuftest für Ziele, die dir egal sind, und die Quelle versiegt in genau dem Maß.",
15:"In dir wohnen Extreme: heute alles, morgen nichts, und beides ist echt. Diese Bandbreite macht dich zutiefst menschlich, denn du verstehst jeden Zustand von innen. Der Schatten: Du misst dich am gleichmäßigen Takt der anderen und hältst deine Spannweite für einen Defekt.",
16:"Begeisterung ist dein Treibstoff, und Können ist dein Ziel. Du willst nicht nur reden, du willst meistern, üben, verfeinern, bis aus Enthusiasmus Kunst wird. Der Schatten: Du springst begeistert los, bevor die Tiefe da ist, und verkaufst Talent als Meisterschaft.",
17:"Du baust Meinungen wie Architekturen: begründet, geprüft, belastbar. Deine Sicht auf Dinge gibt anderen Struktur im Nebel. Der Schatten: Aus der Meinung wird eine Festung, und du verteidigst Mauern, wo ein Fenster klüger wäre.",
18:"Dein Blick findet den Fehler im Muster, die Stelle, an der es besser ginge. Das ist keine Nörgelei, das ist eine Gabe im Dienst der Freude: Korrigiert wird, damit es wieder fließt. Der Schatten: Du richtest den Korrekturblick auf dich selbst und auf Menschen, die nie um Prüfung gebeten haben.",
19:"Du spürst, was gebraucht wird, bevor es jemand ausspricht: Nähe, Nahrung, Zugehörigkeit. Deine Sensibilität ist die Grundlage jeder Gemeinschaft. Der Schatten: Du machst dich klein, um dazuzugehören, und nennst den Preis dafür zu spät.",
20:"Du bist ganz im Jetzt oder gar nicht. Was du sagst und tust, hat nur Kraft, wenn es aus diesem Moment kommt, ungeplant und wach. Der Schatten: Du verwechselst Beschäftigtsein mit Präsenz und redest im Jetzt über Dinge, die längst vorbei sind.",
21:"Du brauchst die Kontrolle über dein eigenes Revier: dein Geld, deine Arbeit, dein Zuhause, deine Regeln. Das ist kein Machthunger, das ist deine Bauart. Der Schatten: Du kontrollierst fremde Reviere mit, und der Kampf, der daraus entsteht, ist immer verloren.",
22:"Anmut ist deine Art, mit der Welt zu sprechen: ein Charme, der Türen öffnet, wenn deine emotionale Welle es erlaubt. Du machst Schweres leicht, wenn du in Stimmung bist. Der Schatten: Erzwungene Freundlichkeit im emotionalen Tief, die dich innerlich doppelt kostet.",
23:"Du übersetzt Komplexes in einfache Sätze, die sitzen. Was in deinem Kopf zusammenschießt, kann für andere zur Erkenntnis werden, wenn der Moment reif ist. Der Schatten: Ungefragt geteilt klingt deine Einsicht wie Anmaßung, und man erklärt dich zum Sonderling statt zum Erklärer.",
24:"Dein Denken kehrt zurück, immer wieder, zur selben Frage, bis sie sich in Erkenntnis verwandelt. Dieses Kreisen ist kein Grübeln, es ist Reifung. Der Schatten: Die Schleife dreht ohne Ausgang, und du verwechselst das Rattern im Kopf mit Fortschritt.",
25:"In dir lebt eine Unschuld, die nicht naiv ist: eine Liebe ohne Adresse, die allem gilt, was lebt. Menschen fühlen sich in deiner Nähe seltsam gemeint. Der Schatten: Verwundungen können diese Offenheit vernarben lassen, und du liebst auf Sparflamme, um nicht wieder getroffen zu werden.",
26:"Du kannst verkaufen: Ideen, Dinge, dich selbst, im besten Sinn. Du weißt, wie man Wahrheit so verpackt, dass sie ankommt, und wie man mit wenig Aufwand viel bewegt. Der Schatten: Die Abkürzung wird zur Gewohnheit, und aus geschickt wird irgendwann unaufrichtig.",
27:"Fürsorge ist dein Urinstinkt: nähren, schützen, aufpäppeln, was schwach ist. Bei dir werden Menschen satt, im wörtlichen wie im übertragenen Sinn. Der Schatten: Du fütterst alle außer dich selbst und kümmerst dich um Menschen, die nie darum gebeten haben.",
28:"Du spielst um das, was zählt: Dieses Tor fragt, wofür sich das Leben lohnt, und riskiert lieber etwas, als sinnlos sicher zu bleiben. Der Kampf um Sinn ist dein Lebensgefühl. Der Schatten: Du kämpfst gegen alles, nur um zu spüren, dass du lebst, und nennst die Erschöpfung danach Tiefe.",
29:"Dein Ja hat Gewicht: Wenn du dich verpflichtest, gehst du durch, wo andere längst umgedreht haben. Ausdauer ist deine Superkraft. Der Schatten: Du sagst Ja aus Reflex, zu allem und jedem, und deine legendäre Ausdauer bindet dich an Dinge, die dich leeren.",
30:"In dir brennt eine Sehnsucht, die nie ganz gestillt wird, und genau das ist ihre Aufgabe: Sie hält dich lebendig, hungrig auf Erfahrung. Gefühle haben bei dir Temperatur. Der Schatten: Du hängst dein Glück an das Eintreffen einer bestimmten Erwartung, und das Leben kann nur enttäuschen.",
31:"Deine Stimme ist zum Führen gebaut: Wenn eine Gruppe dich wählt, kannst du aussprechen, was die Mehrheit braucht. Einfluss ist bei dir Amt, nicht Anspruch. Der Schatten: Du sprichst für Menschen, die dich nicht gewählt haben, und deine Worte fallen zu Boden.",
32:"Du erkennst instinktiv, was Bestand haben wird und was nicht: welches Projekt trägt, welcher Mensch bleibt, welche Investition hält. Kontinuität ist dein Kompass. Der Schatten: Die Angst zu versagen wird lauter als der Instinkt, und du bewahrst aus Furcht, was längst gehen dürfte.",
33:"Nach jeder Erfahrung brauchst du den Rückzug, in dem aus Erlebtem Erinnerung wird und aus Erinnerung Weisheit. Du bist das Gedächtnis deiner Welt. Der Schatten: Der Rückzug wird zur Flucht, und deine Geschichten bleiben unerzählt, wo sie anderen den Weg zeigen könnten.",
34:"Reine Kraft wohnt in dir: die Macht, zu tun, ausdauernd und unabhängig. Wenn sie auf das antwortet, was wirklich ruft, bist du unaufhaltsam. Der Schatten: Kraft ohne Antwort wird zur Betriebsamkeit, und du bist ständig beschäftigt, ohne dass etwas Wichtiges geschieht.",
35:"Du hungerst nach Erfahrung: einmal alles probieren, fühlen, durchleben. Fortschritt heißt für dich nicht besser, sondern weiter. Aus deiner Sammlung an Erlebtem wirst du weise. Der Schatten: Nichts schmeckt beim zweiten Mal, und du jagst Neues, um die Leere nach dem Letzten zu füllen.",
36:"Du wächst durch Krisen, die andere meiden: emotionale Tiefe entsteht bei dir im Sturm, nicht in der Flaute. Nach jedem Durchgang kannst du mehr halten. Der Schatten: Du zettelst Stürme an, wenn es zu ruhig wird, und verwechselst Drama mit Tiefgang.",
37:"Du hältst Gemeinschaften zusammen: mit Wärme, mit Verlässlichkeit, mit dem Gespür für faire Abmachungen. Familie ist bei dir, wo dein Handschlag gilt. Der Schatten: Du gibst, ohne die Abmachung zu klären, und die stille Rechnung, die daraus wächst, vergiftet die Nähe.",
38:"Du bist zum Kämpfen gebaut, aber nur für das Würdige: Widerstand zeigt dir, was dir etwas bedeutet. Ohne Gegenwind weißt du nicht, wer du bist. Der Schatten: Du kämpfst jeden Kampf, der sich anbietet, und verwechselst Sturheit mit Charakter.",
39:"Du provozierst, und das ist eine Kunst: Dein Stachel findet, wo bei anderen Lebensgeist verschüttet liegt, und reizt ihn wach. Du bist der Frosch, der den Teich testet. Der Schatten: Du stichelst aus eigener Unruhe, und statt Geist weckst du nur Gereiztheit.",
40:"Du lieferst, und dann brauchst du das Alleinsein wie Brot: Arbeit für die Gemeinschaft, Erholung nur für dich. Dieses Wechselspiel ist dein Vertrag mit der Welt. Der Schatten: Du arbeitest für Dank, der nie genug sein kann, oder du verweigerst dich ganz und nennst es Grenze.",
41:"In dir beginnt jede Geschichte: die Fantasie, wie es sein könnte, der Hunger auf eine neue Erfahrung, die noch keinen Namen hat. Du träumst Anfänge, die andere dann leben. Der Schatten: Du hortest tausend Anfänge und beginnst keinen, weil der Traum im Kopf sicherer scheint als der erste Schritt.",
42:"Du bist zum Vollenden geboren: Zyklen zu Ende bringen, damit Neues Platz hat. Wachstum geschieht bei dir im letzten Drittel, dort, wo andere abspringen. Der Schatten: Halbfertiges stapelt sich, und jedes offene Ende zieht leise Kraft, wie ein Fenster, das nie schließt.",
43:"Einsichten kommen bei dir wie ein Knacken im Ohr: plötzlich, von innen, ohne Herleitung. Du denkst nicht in Schritten, du denkst in Durchbrüchen. Der Schatten: Du erklärst dein inneres Wissen zur Pflicht für alle und wirst nicht gehört, weil der Moment nicht deiner war.",
44:"Du erinnerst dich mit der Nase: Muster aus der Vergangenheit steigen in dir auf wie Gerüche, und du erkennst sofort, wer zu was fähig ist. Personalinstinkt ist deine Gabe. Der Schatten: Die Angst, dass sich Altes wiederholt, liest überall Gespenster von gestern in die Menschen von heute.",
45:"Du bist zum Versammeln geboren: Menschen, Mittel, Territorium. Wie eine gute Königin regierst du am besten, wenn du nicht selbst schuftest, sondern den Rahmen hältst, in dem andere gedeihen. Der Schatten: Herrschaft ohne Dienst wird Besitzdenken, und dein Reich wird einsam.",
46:"Dein Körper ist kein Fahrzeug, er ist der Ort des Geschehens: Du bist zur rechten Zeit am rechten Ort, wenn du ihm folgst statt ihn zu übergehen. Glück findet dich körperlich. Der Schatten: Du lebst vom Hals aufwärts, und die Zufälle, die dich tragen würden, gehen an dir vorbei.",
47:"Deine Verwirrung ist ein Verdauungsorgan: Erlebtes braucht bei dir Zeit, bis aus dem Wirrwarr plötzlich Sinn aufsteigt, oft Jahre später. Du realisierst rückwärts. Der Schatten: Du presst auf sofortige Klarheit und erklärst den Zwischenzustand zum Beweis, dass mit dir etwas nicht stimmt.",
48:"In dir liegt ein Brunnen: Tiefe, aus der echte Lösungen steigen, wenn man dich schöpfen lässt. Du weißt mehr, als du zeigen kannst. Der Schatten: Die Angst, nicht genug zu wissen, hält dich vom Sprechen ab, ausgerechnet dich, dessen Tiefe alle brauchen.",
49:"Du kennst deine Prinzipien und die Grenze, ab der du gehst: Revolution beginnt bei dir mit einem stillen Nein. Wer deine Grundsätze achtet, bekommt unerschütterliche Loyalität. Der Schatten: Du erhebst Empfindlichkeit zum Prinzip und verstößt Menschen für Kleinigkeiten aus deinem Reich.",
50:"Du hütest die Werte deiner Gemeinschaft: was sich gehört, was Schutz verdient, wofür man einsteht. Verantwortung ist bei dir kein Wort, sondern ein Instinkt. Der Schatten: Du übernimmst Verantwortung, die niemand dir gab, und die Last fremder Pflichten drückt dich krumm.",
51:"Du bist der Schock, der weckt: mutig, sprunghaft, immer einen Schritt vor der Angst der anderen. Deine Erschütterungen bringen Menschen näher zu ihrem eigenen Geist. Der Schatten: Schock um des Schocks willen, und aus dem Wecker wird ein Störer.",
52:"Stille ist deine Stärke: die Fähigkeit, wie ein Berg zu sitzen und die Energie zu bündeln, bis der eine richtige Fokus sich zeigt. Deine Ruhe ist gespannte Kraft, keine Trägheit. Der Schatten: Angestaute Unruhe, wenn kein Fokus da ist, und du sitzt fest statt still.",
53:"Du beginnst: Jeder neue Zyklus in deiner Umgebung trägt deinen Fingerabdruck. Anfangen ist dein Beitrag, Vollenden oft der Job anderer, und das ist Arbeitsteilung, keine Schwäche. Der Schatten: Die Scham über Unvollendetes, als wärst du deinen eigenen Anfängen etwas schuldig.",
54:"Ehrgeiz treibt dich nach oben, und zwar den echten: den Hunger, aus dem Gegebenen mehr zu machen, materiell wie geistig. Du bist die Ameise mit dem Traum vom Adler. Der Schatten: Aufstieg um jeden Preis, und oben angekommen weißt du nicht mehr, wofür du geklettert bist.",
55:"Deine Stimmung ist ein Geist, der kommt und geht, ohne Grund und ohne Schuld. In der Fülle deiner Welle liegt Musik, in ihrer Leere liegt Tiefe. Beides gehört dir. Der Schatten: Du suchst den Schuldigen für jedes Tief, bei dir oder bei anderen, dabei will die Welle nur durchziehen.",
56:"Du bist die Geschichtenerzählerin am Feuer: Erlebtes wird in dir zu Erzählung, und deine Anregung hält Gespräche und Köpfe in Bewegung. Der Schatten: Du erzählst, um Aufmerksamkeit zu halten, statt weil eine Geschichte reif ist, und deine besten wirken abgenutzt.",
57:"Deine Intuition ist ein Ohr für den Moment: ein leises, klares Signal, das jetzt spricht und sich nicht wiederholt. Sie hört Gefahr und Chance, bevor der Verstand aufwacht. Der Schatten: Die Angst vor der Zukunft übertönt das Jetzt, und du hörst Bedrohungen, wo dein Ohr nur Wachheit meinte.",
58:"In dir sprudelt Lebensfreude mit einem Auftrag: Sie will, dass es besser wird, schöner, lebendiger. Deine Vitalität ist die Energie hinter jeder Verbesserung. Der Schatten: Freudloses Korrigieren, wenn die Quelle verschüttet ist, dann nörgelt die Vitalität statt zu tanzen.",
59:"Du bist gebaut, Barrieren aufzulösen: Deine Aura kommt näher, als Menschen gewohnt sind, und schafft die Nähe, aus der Vertrauen und Leben entstehen. Intimität ist dein Terrain. Der Schatten: Nähe als Strategie, und Menschen spüren den Zweck hinter der Wärme.",
60:"Du machst aus Begrenzung Musik: Wie ein Gedicht durch seine Form lebt, wird bei dir aus dem Angenommenen das Neue. Mutation braucht deinen Realismus. Der Schatten: Du starrst auf das, was nicht geht, und die Begrenzung, die dein Sprungbrett wäre, wird zur Zellentür.",
61:"Dein Geist will hinter die Dinge: Warum ist alles so, was steckt dahinter, was ist wirklich wahr? Diese innere Wahrheit kommt als Inspiration, nicht als Ergebnis. Der Schatten: Der Druck, das Unbeantwortbare beantworten zu müssen, raubt dir Nächte für Fragen ohne Adresse.",
62:"Du gibst den Dingen Namen: Details, Fakten, das präzise Wort, das aus Nebel Landkarte macht. Andere verstehen die Welt durch deine Genauigkeit. Der Schatten: Du versteckst dich hinter Fakten, wenn es persönlich wird, und zählst Bäume, wo jemand den Wald von dir wollte.",
63:"Dein Zweifel ist ein Werkzeug, kein Makel: Er prüft jede Behauptung auf Tragfähigkeit und macht die Zukunft sicherer. Skepsis ist deine Form von Fürsorge. Der Schatten: Der Zweifel dreht sich gegen dich selbst und zersetzt, was er prüfen sollte.",
64:"Vor der Klarheit steht bei dir das Bilderrauschen: Erinnerungen, Eindrücke, Sinnfetzen, die sich erst mit der Zeit zu einem Muster fügen. Du musst nichts erzwingen, das Bild entwickelt sich. Der Schatten: Du wühlst im Rauschen nach der Sofortantwort und hältst den Druck im Kopf für deine Schuld."
};

/* Die sechs Linien: Grundtöne, aus denen jedes Profil gebaut ist */
var LINIEN={
1:{name:"Die Forscherin",kern:"Du brauchst ein Fundament, bevor du dich sicher fühlst: verstehen, studieren, dem Grund auf den Grund gehen. Sicherheit entsteht bei dir durch Wissen.",gabe:"Autorität durch echte Substanz",falle:"Endloses Vorbereiten als Versteck vor dem Anfangen"},
2:{name:"Die Einsiedlerin",kern:"Dein Talent ist natürlich und braucht Rückzug, um zu reifen. Andere sehen deine Gabe klarer als du selbst und rufen dich heraus.",gabe:"Müheloses Können, das echt bleibt",falle:"Sich verstecken, bis der richtige Ruf ungehört verhallt"},
3:{name:"Die Entdeckerin",kern:"Du lernst durch Anfassen, Ausprobieren, Scheitern. Was bei dir kaputtgeht, war eine Entdeckung, kein Versagen. Deine Umwege sind die Methode.",gabe:"Unbezahlbare Erfahrung aus erster Hand",falle:"Jeden Bruch als persönliches Scheitern verbuchen"},
4:{name:"Die Netzwerkerin",kern:"Deine Chancen kommen über Menschen, die dich kennen: Freundschaften, Vertrauen, Beziehungen mit Geschichte. Fremden verkaufst du schlecht, Vertrauten alles.",gabe:"Ein tragendes Netz aus echten Verbindungen",falle:"Das Alte loslassen, bevor das Neue steht"},
5:{name:"Die Retterin",kern:"Menschen projizieren Lösungen auf dich, oft bevor du ein Wort gesagt hast. Du kannst liefern und wirst dafür verehrt, oder enttäuschen und dafür verbrannt.",gabe:"Praktische Führung in der Krise",falle:"Jede Projektion annehmen, auch die unerfüllbaren"},
6:{name:"Das Vorbild",kern:"Dein Leben hat drei Akte: erst hineinspringen und anecken, dann vom Dach aus beobachten, dann als gelebtes Beispiel wieder herabsteigen. Vertrauen ist deine Währung.",gabe:"Weisheit, der man glaubt, weil sie gelebt ist",falle:"Auf dem Dach wohnen bleiben, wenn das Leben ruft"}
};

return {TOR_TEXTE:TOR_TEXTE,LINIEN:LINIEN};
});
